[general]
  import = [
    "~/.config/alacritty/themes/base16-3024.toml",
    #"~/.config/alacritty/themes/acme.toml",
    #"~/.config/alacritty/themes/base16_default_dark.toml",
    #"~/.config/alacritty/themes/Cobalt2.toml",
    #"~/.config/alacritty/themes/gruvbox_dark.toml",
    "~/.config/alacritty/keybindings.toml",
  ] 

  working_directory  = "~"
  live_config_reload = true

[env]
  MY_ENV_VAR = "mev"

[window]
  padding = { x = 5, y = 4 }
  opacity = 0.6
