""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" COLORSCHEMES 
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd FileType c 		    colorscheme desert
autocmd FileType javascript colorscheme gruvbox
autocmd FileType markdown 	colorscheme default
autocmd FileType python 	colorscheme desert
autocmd FileType sh 		colorscheme murphy
autocmd FileType text 		colorscheme habamax
autocmd FileType vim 		colorscheme default
syntax  on

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" SETTINGS
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set splitbelow splitright

set colorcolumn=64
hi ColorColumn ctermbg=darkgrey guibg=darkgrey

set noswapfile

set autoindent
set expandtab
set softtabstop=4
set tabstop=4

set hlsearch
set incsearch

set nowrap

set timeout timeoutlen=3000 ttimeoutlen=100

set number
set relativenumber


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" MAPPINGS
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let mapleader = " "
" Use "Very Magic" regex searching
nnoremap / /\v
nnoremap <C-s> :nohls<CR>:w<CR>
inoremap <C-s> <Esc>l:nohls<CR>:w<CR>
nnoremap <Leader>s :source $MYVIMRC<CR>:echo "\<Leader\>s"$MYVIMRC<CR>
nnoremap ,s :source $MYVIMRC<CR>:echo ",s"$MYVIMRC<CR>
nnoremap ,c :vs $MYVIMRC<CR>

nnoremap <Tab> <C-w><C-w>
nnoremap <S-Tab>   i<Tab><Esc>
"nnoremap <S-Space> i        
nnoremap <Bs> i<Bs><Esc>

nnoremap <Leader>bn :bn<CR>
nnoremap <Leader>bp :bn<CR>

" Toggle line numbers with Ctrl-n
nnoremap <C-n> :call ToggleLineNumbers()<CR>

function! ToggleLineNumbers()
  if &number
    setlocal nonumber
    setlocal norelativenumber
  else
    setlocal number
    setlocal relativenumber
  endif
endfunction
