#!/usr/bin/env bash

#sxhkd is started with ~/.config/x11/.xinitrc
#Use super + ctrl + r   to reload sxhkd
#Use super + alt  + r   to reload bspwm

bspc monitor eDP1 -d 1 2
bspc monitor HDMI1 -d 3 4

bspc config border_width                        3
bspc config window_gap                         13

bspc config normal_border_color          '#3a3432'
bspc config active_border_color          '#01a252'
bspc config focused_border_color         '#01a252'
bspc config preselect_feedback_color     '#00ff88'

bspc config split_ratio                     0.50
bspc config borderless_monocle              true
bspc config gapless_monocle                 true

bspc rule -a firefox desktop='^4'

bspc subscribe layout | while read -r monitor desktop layout; do
    if [ "$layout" = "monocle" ]; then
        # Monocle mode → deep blue border
        bspc config focused_border_color "#005577"
        bspc config normal_border_color "#003344"
    else
        # Tiled mode → your normal colors
        bspc config focused_border_color "#88c0d0"
        bspc config normal_border_color "#4c566a"
    fi
done &
