###########################################
##  PREFIX = Alt+Space
############################################
unbind-key C-b
set -g prefix M-Space
bind-key M-Space send-prefix


############################################
##  GLOBAL SETTINGS
############################################
set -g base-index 1
setw -g pane-base-index 1
set-option -g focus-events on
set-option -g mode-keys vi

-n M-s

###########################################
##  SOURCE
############################################
# Alt+s
bind-key -n M-s source-file ~/.config/tmux/tmux.conf \; display-message "Sourced"
bind-key -n M-s source-file ~/.config/tmux/tmux.conf \; display-message "Sourced"
# Prefix+s
bind-key s      source-file ~/.config/tmux/tmux.conf \; display-message "Sourced" |


###########################################
##  PANES
############################################
# Prefix+|/-    &   Alt+|/-
bind-key      | split-window -h
bind-key      - split-window -v
# Alt+|/-       Only works in gui mode
bpnd-key -M-| split-window -h
bpnd-key  M --| split-window -h
bind-key -n M-- split-window -v

# Alt+hjkl
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

# Alt+Shift+HJKL
bind-key -n M-H resize-pane -L 2
bind-key -n M-J resize-pane -D 2
bind-key -n M-K resize-pane -U 2
bind-key -n M-L resize-pane -R 2


############################################
##  WINDOWS
############################################
# Alt + w       New Window
bind-key -n M-w new-window

# Alt + 1234    Select Window
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4


############################################
##  COPY AND PASTE
############################################
# Alt+c     Enter Copy Mode
bind-key -n M-c copy-mode
# Alt+v:    Begin selection directly from normal mode
bind-key -n M-v copy-mode \; send -X begin-selection
# when in copy-mode: v begin selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
# when in copy-mode: y yank and exit copy-mode
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
# Alt+p     Put in normal mode
bind-key -n M-p paste-buffer

 
############################################
##  STATUS LINE
############################################
# Same blue color as the default DWM bar
#set -g status-bg "#005577"
set -g status-bg "#222222"
# Same white color as the default DWM foreground
set -g status-fg "#eeeeee"
set -g status-left  "#[bg=#000000,fg=#eeeeee] #S "
set -g status-right "#[bg=#000000,fg=#eeeeee] %Y-%m-%d %H:%M %a "



#---------------------------------------------------------------------
############################################
## USER KEYS FROM TTY
############################################
#set -s user-keys[0] "\e[25~"
#set -s user-keys[0] "\e[26~"
##set -s user-keys[0] "^[[25~"
##set -s user-keys[1] "^[[26~"
##set -s user-keys[0] "\e[1:2P"
##set -s user-keys[1] "\e[1:2Q"
#
#bind-key User0 split-window -h
#bind-key User1 split-window -v
#bind-key -n M-v split-window -h
#bind-key -n M-h split-window -v
