###########################################
##  PREFIX ALT + B
############################################
unbind-key C-b
set -g prefix M-b
bind-key M-b send-prefix


############################################
##  GLOBAL SETTINGS
############################################
set -g base-index 1
setw -g pane-base-index 1
set-option -g focus-events on
set-option -g mode-keys vi


############################################
##  BINDINGS
############################################
# Alt + w       New Window
bind-key -n M-w new-window

# Alt + 1234    Select Window
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4

# Alt+c Enter Copy Mode
bind-key -n M-c copy-mode
# Alt+v: begin selection directly from normal mode
bind-key -n M-v copy-mode \; send -X begin-selection
# v: begin selection when in copy-mode
bind-key -T copy-mode-vi v send -X begin-selection
# when in copy-mode: yank and exit copy-mode
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
# Alt + p put in normal mode
bind-key -n M-p paste-buffer

############################################
##  NAVIGATIONS
############################################
# Alt + | (pipe) to split vertically
bind-key -n M-| split-window -h \; display-message "Alt + |"
# Alt + - (dash) to split horizontally
bind-key -n M-- split-window -v \; display-message "Alt + -"
# Prefix + |    Alt + B + |
bind-key | split-window -h
# Prefix + -    Alt + B + -
bind-key - split-window -v

# Alt + hjkl naviagates panes
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

bind-key -n M-H resize-pane -L 2
bind-key -n M-J resize-pane -D 2
bind-key -n M-K resize-pane -U 2
bind-key -n M-L resize-pane -R 2

# Alt + uiop resize panes
#bind-key -n M-u resize-pane -L 3
#bind-key -n M-i resize-pane -D 3
#bind-key -n M-o resize-pane -U 3
#bind-key -n M-p resize-pane -R 3

# Alt + s   source tmux.conf
bind-key -n M-s source-file ~/.config/tmux/tmux.conf \; display-message "Sourced"

 
############################################
##  STATUS LINE
############################################
# Same blue color as the default DWM bar
#set -g status-bg "#005577"
set -g status-bg "#222222"
# Same white color as the default DWM foreground
set -g status-fg "#eeeeee"
set -g status-left  "#[bg=#000000,fg=#eeeeee] #S "
set -g status-right "#[bg=#000000,fg=#eeeeee] %Y-%m-%d %H:%M %a "
