###########################################
##  PREFIX = Alt+Space
############################################
set-option -g prefix M-Space
unbind-key C-b
bind-key M-Space send-prefix



############################################
##  GLOBAL set-optionTINGS
############################################
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g focus-events on
set-option -g mode-keys vi


###########################################
##  SOURCE
############################################
# Ctrl + Alt + r
bind-key -n M-C-r source-file ~/.config/tmux/tmux.conf \; display-message "Sourced"
# Alt + r
bind-key -n M-r   source-file ~/.config/tmux/tmux.conf \; display-message "Sourced"
# Prefix + r
bind-key r        source-file ~/.config/tmux/tmux.conf \; display-message "Sourced"


###########################################
##  PANES
############################################
# Alt+|/-       For GUI mode
bind-key -n M-| split-window -h
bind-key -n M-- split-window -v
#
bind-key -Troot M-` split-window -h
bind-key -Troot M-/ split-window -v

# Define a custom user keys for the Linux console's F13&F14 sequences
set-option -s user-keys[0] "\033[25~"
set-option -s user-keys[1] "\033[26~"
# Bind it
bind-key -n User0 split-window -h
bind-key -n User1 split-window -v
#bind-key -n User0 display-message "User0 pressed"

# Prefix+|/-    Works in non-gui and gui mode
bind-key      | split-window -h
bind-key      - split-window -v


# Alt+hjkl
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

# Alt+Shift+HJKL
bind-key -n M-H resize-pane -L 1
bind-key -n M-J resize-pane -D 1
bind-key -n M-K resize-pane -U 1
bind-key -n M-L resize-pane -R 1

# Alt+m toggle monocle
bind-key -n M-m resize-pane -Z

############################################
##  WINDOWS
############################################
# Alt + w       New Window
bind-key -n M-w new-window

# Alt + 1234    Select Window
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4


############################################
##  COPY AND PASTE
############################################
# Alt+c     Enter Copy Mode
bind-key -n M-c copy-mode
# Alt+v:    Begin selection directly from normal mode
bind-key -n M-v copy-mode \; send-keys -X begin-selection
# when in copy-mode: v begin selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
# when in copy-mode: y yank and exit copy-mode
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# Escape to cancel copy mode
bind-key -T copy-mode-vi Escape send-keys -X cancel
# Alt+p     Put in normal mode
bind-key -n M-p paste-buffer

 
############################################
##  STATUS LINE
############################################
# Same blue color as the default DWM bar
#set -g status-bg "#005577"
set -g status-bg "#222222"
# Same white color as the default DWM foreground
set -g status-fg "#eeeeee"
set -g status-left  "#[bg=#000000,fg=#eeeeee] #S "
set -g status-right "#[bg=#000000,fg=#eeeeee] %Y-%m-%d %H:%M %a "



#---------------------------------------------------------------------
############################################
## USER KEYS FROM TTY
############################################
#set -s user-keys[0] "\e[25~"           F13
#set -s user-keys[0] "\e[26~"|          F14
##set -s user-keys[0] "^[[25~"
##set -s user-keys[1] "^[[26~"
##set -s user-keys[0] "\e[1:2P"         F13
##set -s user-keys[1] "\e[1:2Q"         F14
#
#bind-key User0 split-window -h
#bind-key User1 split-window -v
#bind-key -n M-v split-window -h
#bind-key -n M-h split-window -v
