#!/usr/bin/env bash

alias b="bat"
alias c="f_cdls"
alias er="nvim $XDG_CONFIG_HOME/bash/bashrc && source $HOME/.bashrc"
alias sr="clear && source $HOME/.bashrc"
alias l="eza -lAh --icons=auto --git --sort modified -r"
alias mkcd="f_mkcd"
alias t="tmux"
alias v="nvim"
alias vf="vifm"
alias x="startx"
alias pm="sudo pacman"
