#!/usr/bin/env bash
#
# see also the settings in ~/.config/readline/
#
echo " ~/.config/bash/bashrc"
#
# Load modular components
for file in ~/.config/bash/{exports,aliases,functions,prompt,completion}; do
    [ -f "$file" ] && source "$file"
done

# Make CapsLock a secondary Escape key
#sudo loadkeys $XDG_CONFIG_HOME/kbd/esc.map
#sudo loadkeys $XDG_CONFIG_HOME/kbd/custom.map
# /usr/local/share/kbd/keymaps/no-custom.map.gz
# /etc/vconsole.conf    ->  KEYMAP=no-custom

# Make ctrl+s useable
stty -ixon

# Uncomment to add debug info
#source ~/.config/bash/debug

#fastfetch
#neofetch
