#!/usr/bin/env bash
#echo " ~/.config/bash/bashrc"

# see also the settings in ~/.config/readline/

# Load modular components
for file in ~/.config/bash/{exports,functions,aliases,completion,prompt}; do
    [ -f "$file" ] && source "$file"
done


# Make ctrl+s useable
stty -ixon


#################################################
##  DEBUG
#################################################
source ~/.config/bash/debug
source ~/.config/bash/important

