#!/usr/bin/env bash
#
# see also the settings in ~/.config/readline/
#
echo " ~/.config/bash/bashrc"
#
# Load modular components
for file in ~/.config/bash/{exports,aliases,functions,prompt,completion}; do
    [ -f "$file" ] && source "$file"
done
#
# Make CapsLock a secondary Escape key
sudo loadkeys $XDG_CONFIG_HOME/kbd/esc.map
sudo loadkeys $XDG_CONFIG_HOME/kbd/custom.map
# Make ctrl+s useable
stty -ixon

# Uncomment to turn on debugging
source ~/.config/bash/debug

#fastfetch
#neofetch
