#!/usr/bin/env bash
if [[ "$DEBUG" == "true" ]]; then
    #         1         2         3         4         5         6  
    #1234567890123456789012345678901234567890123456789012345678901234567890
    printf "                -> ~/.config/bash/completion     \$- $-\n"
fi

# Extra bash completions goes here
# Can all completions be set with readline?
export HISTCONTROL=ignoreboth
