#!/usr/bin/env bash

echo " ~/.config/debug"

echo "TERM              = $TERM"
echo "TERMINAL          = $TERMINAL"
echo "SHELL             = $SHELL"
echo "INPUTRC           = $INPUTRC"

echo "BROWSER           = $BROWSER"
echo "EDITOR            = $EDITOR"
echo "HOME              = $HOME"
echo "XDG_CONFIG_HOME   = $XDG_CONFIG_HOME"
echo "XDG_STATE_HOME    = $XDG_STATE_HOME"
echo "XDG_DATA_HOME     = $XDG_DATA_HOME"
echo "XAUTHORITY        = $XAUTHORITY"
echo "XINITRC           = $XINITRC"

echo '  ip a '
echo '  rc-status '
echo '  #rc-service iwd start '
echo '  #rc-update del iwd '
echo '  #rc-update add default '
echo '  iwctl station wlan0 connect "103B 5"  '
