#!/usr/bin/env bash
# vim: filetype=sh :

export BROWSER         = "/usr/bin/firefox"
export EDITOR          = "/usr/bin/nvim"
export INPUTRC         = "$XDG_CONFIG_HOME/readline/inputrc"
export MANPAGER        = "bat -plman"
export PATH            = "$XDG_STATE_HOME/bin:$PATH"
export XAUTHORITY      = "$XDG_CONFIG_HOME/x11/.Xauthority"
export XDG_CONFIG_HOME = "$HOME/.config"
export XDG_STATE_HOME  = "$HOME/.local"
export XINITRC         = "$XDG_CONFIG_HOME/x11/.xinitrc"

# don't save duplicates and commands starting with a space
export HISTCONTROL=ignoreboth
