#!/usr/bin/env bash
printf "                        ~/.config/bash/exports       \$- $-\n"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local"

#export BROWSER="/usr/bin/firefox
#export SXHKD_SHELL="/usr/bin/dash"
#printf "~/.config/bash/exports\n"
yyyymm=$(date +%Y.%m)

export ARCH_VERSION="$yyyymm.01"
export BROWSER="/usr/bin/firefox"
export BSPC="/usr/bin/bspc"
export EDITOR="/usr/bin/nvim"
export GDBINIT="$XDG_CONFIG_HOME/gdb/gdbinit"
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export MANPAGER="batman"
export PATH="$XDG_STATE_HOME/bin:$PATH"
export SXHKD_SHELL="/usr/bin/bash"
export TERMINAL="/usr/bin/alacritty"
export W3M_DIR="$XDG_CONFIG_HOME/w3m"
export XAUTHORITY="$XDG_CONFIG_HOME/x11/.Xauthority"
export XINITRC="$XDG_CONFIG_HOME/x11/.xinitrc"
