#!/usr/bin/env bash

f_eza() {
  command eza              \
    --almost-all            \
    --git                    \
    --group-directories-first \
    --icons=auto               \
    --sort=name                 \
    --time-style=iso             \
    "$@"                          \
    || return
        
    git status --short 2>/dev/null
}

f_cdls() {
    if [ -n "$1" ]; then
        # if argument is given cd into directory
        cd "$1"
    else
        # if no argument, cd $HOME
        cd ~
    fi
    # Always list directory
    f_eza
}

f_mkcd() {
    # Make given directory
    mkdir -p "$1" || return
    # Cd into the new directory and list (check it it empty)
    f_cdls "$1"
}


f_update() {
    if command -v paru >/dev/null 2>&1; then
        echo "Using paru -Syu"
        paru -Syu
    else
        echo "Using pacman -Syu"
        sudo -v
        sudo pacman -Syu
    fi
}

f_edit_bash() {
    echo "f_edit_bash()"
} 
