#!/usr/bin/env bash
#source ~/.config/bash/exports
echo "$XDG_CONFIG_HOME/bash/functions"
null="/dev/null"

f_eza() {
  command eza              \
    --almost-all            \
    --git                    \
    --group-directories-first \
    --icons=auto               \
    --sort=name                 \
    --time-style=iso             \
    "$@"                          \
    || return
        
    git status --short 2>$null
    git remote --verbose 2>$null
}

f_cdls() {
    if [ -n "$1" ]; then
        # if argument is given cd into directory
        cd "$1"
    else
        # if no argument, cd $HOME
        cd ~
    fi
    # Always list directory
    f_eza
}

f_mkcd() {
    # Make given directory
    mkdir -p "$1" || return
    # Cd into the new directory and list (check it it empty)
    f_cdls "$1"
}


f_pacman() {
    if command -v paru >/dev/null 2>&1; then
        echo "Using: paru"
        paru "$@" --needed
    else
        echo "Using: sudo pacman"
        sudo -v
        sudo pacman "$@" --needed
    fi
}

f_edit_bash() {
    echo "f_edit_bash()"
    echo "XDG_CONFIG_HOME=$XDG_CONFIG_HOME"
    exec nvim $XDG_CONFIG_HOME/bash/aliases    \
         $XDG_CONFIG_HOME/bash/functions  \
         $XDG_CONFIG_HOME/bash/exports    \
         $XDG_CONFIG_HOME/bash/debug      \
         $XDG_CONFIG_HOME/bash/completion \
         $XDG_CONFIG_HOME/bash/prompt     \
         $XDG_CONFIG_HOME/readline/inputrc     \
         $XDG_CONFIG_HOME/readline/options     \
         $XDG_CONFIG_HOME/readline/vi-mode     \
         $XDG_CONFIG_HOME/readline/keybind     \
         $XDG_CONFIG_HOME/readline/completions \
          && source $HOME/.bashrc
} 
