#!/usr/bin/env bash
echo "~/.config/bash/functions"

#source ~/.config/bash/exports
null="/dev/null"

f_eza() {
  command eza              \
    --almost-all            \
    --git                    \
    --group-directories-first \
    --icons=auto               \
    --sort=name                 \
    --time-style=iso             \
    "$@"                          \
    || return
        
    git status --short 2>$null
    git remote --verbose 2>$null
}

f_cdls() {
    if [ -n "$1" ]; then
        # if argument is given cd into directory
        cd "$1"
    else
        # if no argument, cd $HOME
        cd ~
    fi
    # Always list directory
    f_eza
}

f_mkcd() {
    # Make given directory
    mkdir -p "$1" || return
    # Cd into the new directory and list (check it it empty)
    f_cdls "$1"
}


f_pacman() {
    if command -v paru >$null 2>&1; then
        echo "Using: paru"
        #paru "$@" --color=auto
        paru "$@"
    else
        echo "Using: sudo pacman"
        sudo -v
        #sudo pacman "$@" --color=auto
        sudo pacman "$@"
    fi
}

f_edit_bash() {
    $EDITOR $XDG_CONFIG_HOME/bash/bash_profile \
            $XDG_CONFIG_HOME/bash/bashrc       \
            $XDG_CONFIG_HOME/bash/exports      \
            $XDG_CONFIG_HOME/bash/aliases      \
            $XDG_CONFIG_HOME/bash/bash_logout  \
            $XDG_CONFIG_HOME/bash/completion   \
            $XDG_CONFIG_HOME/bash/debug        \
            $XDG_CONFIG_HOME/bash/functions    \
            $XDG_CONFIG_HOME/bash/important    \
            $XDG_CONFIG_HOME/bash/prompt       \
            $XDG_CONFIG_HOME/readline/completions \
            $XDG_CONFIG_HOME/readline/inputrc     \
            $XDG_CONFIG_HOME/readline/keybinds    \
            $XDG_CONFIG_HOME/readline/options     \
            $XDG_CONFIG_HOME/readline/vi-mode     \
                && clear && source $HOME/.bash_profile
} 

f_reboot() {
    iwctl known-networks "103B 5" forget
    sudo reboot
}

f_poweroff() {
    iwctl known-networks "103B 5" forget
    sudo poweroff
}
